name: CI

on: push

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Conan
        run: pip install conan
      - name: Conan profile detect
        run: conan profile detect
      - name: Conan install
        run: conan install . --build=missing --settings build_type=Debug --settings compiler.cppstd=17
      - name: Configure
        run: cmake --preset conan-debug
      - name: Build
        run: cmake --build --preset conan-debug
      - name: Run tests
        run: |
          cd build/Debug
          ctest --output-on-failure

  test-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Conan
        run: pip install conan
      - name: Conan profile detect
        run: conan profile detect
      - name: Conan install
        run: conan install . --build=missing --settings build_type=Debug --settings compiler.cppstd=17
      - name: Configure
        run: cmake --preset conan-default
      - name: Build
        run: cmake --build --preset conan-debug
      - name: Run tests
        run: |
          cd build/default
          ctest --output-on-failure

  test-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Conan
        run: pip install conan
      - name: Conan profile detect
        run: conan profile detect
      - name: Conan install
        run: conan install . --build=missing --settings build_type=Debug --settings compiler.cppstd=17
      - name: Configure
        run: cmake --preset conan-debug
      - name: Build
        run: cmake --build --preset conan-debug
      - name: Run tests
        run: |
          cd build/Debug
          ctest --output-on-failure